lr3-4/website/main/urls.py
"""local URL binding of the application"""

from django.conf import settings
from django.conf.urls.static import static
from django.urls import path

from . import views

urlpatterns = [
    path("", views.index, name="main_page"),
    # path('info', views.about, name='info_page'),
    path("product", views.shop, name="products_page"),
    path("product/<int:id>/", views.product_detail, name="product_detail"),
]


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

lr3-4/website/shopcart/urls.py
from django.urls import path

from shopcart import views

app_name = "cart"

urlpatterns = [
    path("", views.cart_detail, name="cart_detail"),
    path("add/<int:product_id>/", views.cart_add, name="cart_add"),
    path("remove/<int:product_id>/", views.cart_remove, name="cart_remove"),
]

lr3-4/website/website/urls.py
"""URL project configuration"""

from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.auth import views as authViews
from django.urls import include, path

from authorization import views as userViews

urlpatterns = [
    path("admin/", admin.site.urls),
    path("cart/", include("shopcart.urls")),
    path("", include("main.urls")),
    path(
        "sign_in/",
        authViews.LoginView.as_view(template_name="authorization/sign_in.html"),
        name="auth_page",
    ),
    path(
        "exit/",
        authViews.LogoutView.as_view(template_name="main/product.html"),
        name="exit",
    ),
    path("sign_up", userViews.register, name="regis_page"),
]


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

lr3-4/website/shopcart/models.py
#

lr3-4/website/shopcart/forms.py
from django import forms

PRODUCT_QUANTITY_CHOICES = [(i, str(i)) for i in range(1, 21)]


class CartAddProductForm(forms.Form):
    quantity = forms.TypedChoiceField(choices=PRODUCT_QUANTITY_CHOICES, coerce=int)
    update = forms.BooleanField(required=False, initial=False, widget=forms.HiddenInput)

lr3-4/website/shopcart/views.py
from django.shortcuts import get_object_or_404, redirect, render
from django.views.decorators.http import require_POST

from main.models import Product

from .cart import Cart
from .forms import CartAddProductForm


@require_POST
def cart_add(request, product_id):
    cart = Cart(request)
    product = get_object_or_404(Product, id=product_id)
    form = CartAddProductForm(request.POST)
    if form.is_valid():
        cd = form.cleaned_data
        cart.add(product=product, quantity=cd["quantity"], update_quantity=cd["update"])
    return redirect("cart:cart_detail")


def cart_remove(request, product_id):
    cart = Cart(request)
    product = get_object_or_404(Product, id=product_id)
    cart.remove(product)
    return redirect("cart:cart_detail")


def cart_detail(request):
    cart = Cart(request)
    for item in cart:
        item["update_quantity_form"] = CartAddProductForm(
            initial={"quantity": item["quantity"], "update": True}
        )
    return render(request, "shopcart/cart_details.html", {"cart": cart})

lr3-4/website/shopcart/templates/shopcart/cart_details.html
{% extends "main/base.html" %}
{% load static %}

{% block title %}
  <title>Корзина</title>
{% endblock %}

{% block content %}
<div class="container">
      <h2 style="margin-top:20px">Корзина покупок</h2><br>
</div>
<div class="d-flex flex-column flex-md-row align-items-center p-3 px-md-4  bg-white border-bottom shadow-sm" style="margin-bottom:10px">
  <h4 class="text-dark mr-md-auto font-weight-normal" style="margin-right:80px; margin-left:80px">Фото</h4>
  <h4 class="text-dark mr-md-auto font-weight-normal" style="margin-right:80px; margin-left:90px">Товар</h4>
  <h4 class="text-dark mr-md-auto font-weight-normal" style="margin-right:80px; margin-left:110px">Кол-во</h4>
  <h4 class="text-dark mr-md-auto font-weight-normal" style="margin-right:80px; margin-left:40px">Цена за шт</h4>
  <h4 class="text-dark mr-md-auto font-weight-normal" style="margin-right:60px; ">Общая стоимость</h4>
</div>

  <table style="width:1600px; margin-top:20px;">

    <tbody frame="below" style="weight:800px">
      {% for item in cart %}
        {% with product=item.product %}
          <tr class="d-flex flex-column flex-md-row align-items-center p-3 px-md-4  bg-white border-bottom shadow-sm">
            <td style="width:250px;">
              <a href="{{ product.get_absolute_url }}">
                <img style="height:150px" src="{% if product.img %}{{ product.img.url }}{% else %}{% static 'img/no_image.png' %}{% endif %}">
              </a>
            </td>
            <td style="color:#33ab25; width:250px;">{{ product.name }}</td>
            <td style="width:220px">
              <form action="{% url 'cart:cart_add' product.id %}" method="post">
                {{ item.quantity }}<br>
                {{ item.update_quantity_form.quantity }}
                {{ item.update_quantity_form.update }}
                <input class="btn btn-outline-primary" type="submit" value="Обновить">
                {% csrf_token %}
              </form>
            </td>

            <td class="num" style="width:200px; color:#222222;">{{ item.price }} byn</td>
            <td class="num" style="width:330px; color:#222222;">{{ item.total_price }} byn</td>
            <td><a class="btn btn-primary" href="{% url 'cart:cart_remove' product.id %}" type="submit">Удалить</a></td>
          </tr>

        {% endwith %}
      {% endfor %}
    </tbody>
  </table>

<div class="d-flex" style="margin-left:40px; margin-top:40px">
  <p style="font-size:30px; color:#222222;">Итого: {{ cart.get_total_price }} byn
    <p class="d-inline-flex mt-2 mt-md-0 ms-md-auto" style="margin-right:100px">
      <a class="btn btn-primary" style="font-size:25px;" href="#" >Оформить заказ</a>
    </p>
  </p>

</div>
{% endblock %}