lr3-4/website/main/urls.py
"""local URL binding of the application"""

from django.conf import settings
from django.conf.urls.static import static
from django.urls import path

from . import views

urlpatterns = [
    path("", views.index, name="main_page"),
    # path('info', views.about, name='info_page'),
    path("product", views.shop, name="products_page"),
    path("product/<int:id>/", views.product_detail, name="product_detail"),
]


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

lr3-4/website/shopcart/urls.py
from django.urls import path

from shopcart import views

app_name = "cart"

urlpatterns = [
    path("", views.cart_detail, name="cart_detail"),
    path("add/<int:product_id>/", views.cart_add, name="cart_add"),
    path("remove/<int:product_id>/", views.cart_remove, name="cart_remove"),
]

lr3-4/website/website/urls.py
"""URL project configuration"""

from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.auth import views as authViews
from django.urls import include, path

from authorization import views as userViews

urlpatterns = [
    path("admin/", admin.site.urls),
    path("cart/", include("shopcart.urls")),
    path("", include("main.urls")),
    path(
        "sign_in/",
        authViews.LoginView.as_view(template_name="authorization/sign_in.html"),
        name="auth_page",
    ),
    path(
        "exit/",
        authViews.LogoutView.as_view(template_name="main/product.html"),
        name="exit",
    ),
    path("sign_up", userViews.register, name="regis_page"),
]


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

lr3-4/website/main/models.py
"""The composition of the application.
Models that should be stored in the database"""

from django.db import models
from django.urls import reverse


class Product(models.Model):
    PHONE = "phone"
    LAPTOP = "laptop"
    PC = "pc"
    ACC = "accessories"

    CHOICE_GROUP = {
        (PHONE, "phone"),
        (LAPTOP, "laptop"),
        (PC, "pc"),
        (ACC, "accessories"),
    }

    name = models.CharField(max_length=30)
    description = models.TextField()
    price = models.IntegerField()
    availability = models.BooleanField()
    group = models.CharField(max_length=20, choices=CHOICE_GROUP, default=PHONE)
    img = models.ImageField(default="no_image.jpeg", upload_to="product_image")

    class Meta:
        verbose_name = "Товар"
        verbose_name_plural = "Товары"

    def get_absolute_url(self):
        return reverse("product_detail", args=[self.id])

lr3-4/website/main/views.py
"""Aplication logic"""

from django.shortcuts import get_object_or_404, render

from shopcart.forms import CartAddProductForm

from .models import Product


def index(request):
    return render(request, "main/main.html")


def check_product(request):
    return render(request, "main/product.html")


def shop(request):
    product = Product.objects.all()
    context = {"pr": product}
    return render(request, "main/product.html", context)


def product_detail(request, id):
    product = get_object_or_404(Product, id=id)
    cart_product_form = CartAddProductForm()
    return render(
        request,
        "main/product_details.html",
        {"product": product, "cart_product_form": cart_product_form},
    )

lr3-4/website/main/templates/main/base.html
<!DOCTYPE html>
<html lang="ru">
<head>
  <meta charset="UTF-8">
{% block title %}{% endblock %}


  <link rel="icon" href="/static/favicon.png" type="image/png">
  <link rel="shortcut icon" href="/static/favicon.ico" type="img/x-icon">
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css">
  <link href='https://fonts.googleapis.com/css?family=Montserrat:400,700' rel='stylesheet' type='text/css'>
  <link href='https://fonts.googleapis.com/css?family=Open+Sans:400,300,800italic,700italic,600italic,400italic,300italic,800,700,600' rel='stylesheet' type='text/css'>

  <link href="/static/css/bootstrap.css" rel="stylesheet" type="text/css">
  <link href="/static/css/style.css" rel="stylesheet" type="text/css">
  <link href="/static/css/font-awesome.css" rel="stylesheet" type="text/css">
  <link href="/static/css/responsive.css" rel="stylesheet" type="text/css">
  <link href="/static/css/magnific-popup.css" rel="stylesheet" type="text/css">
  <link href="/static/css/animate.css" rel="stylesheet" type="text/css">
  <!-- <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css" integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous"> -->
  <script type="text/javascript" src="/static/js/jquery.1.8.3.min.js"></script>
	<script type="text/javascript" src="/static/js/bootstrap.js"></script>
	<script type="text/javascript" src="/static/js/jquery-scrolltofixed.js"></script>
	<script type="text/javascript" src="/static/js/jquery.easing.1.3.js"></script>
	<script type="text/javascript" src="/static/js/jquery.isotope.js"></script>
	<script type="text/javascript" src="/static/js/wow.js"></script>
	<script type="text/javascript" src="/static/js/classie.js"></script>
	<script type="text/javascript" src="/static/js/magnific-popup.js"></script>
	<script src="/static/contactform/contactform.js"></script>

</head>
<body>

    <div class="d-flex flex-column flex-md-row align-items-center p-3 px-md-4  bg-white border-bottom shadow-sm">
      <img src="/static/img/logo3.png" alt="" style="height:30px; margin-right: 10px">
      <h4 class="my-0 text-dark mr-md-auto font-weight-normal">PCMEGA</h4>
      <nav class="d-inline-flex mt-2 mt-md-0 ms-md-auto">
        <a class="me-4 py-2 text-dark text-decoration-none" href="/"><font size="3">Главная</font></a>
        <a class="me-4 py-2 text-dark text-decoration-none" href="{% url 'products_page' %}"><font size="3">Товары</font></a>

        <a class="me-2 py-2 text-dark text-decoration-none" href="{% url 'cart:cart_detail' %}"><font size="3">Корзина</font></a>
      </nav>

      {% if user.is_authenticated %}
        <button onclick="window.location.href = {% url 'exit' %}" style="font-size:16px" type="submit"
                class="btn btn-outline-info">Выход</button>
        <h5>{{user.get_username}}</h5>
      {% else %}
        <a class="btn btn-outline-primary" href="/sign_in">Вход</a>
      {% endif %}

    </div>

{% block content %}{% endblock %}
<script type="text/javascript">
    $(document).ready(function(e) {

      $('#test').scrollToFixed();
      $('.res-nav_click').click(function() {
        $('.main-nav').slideToggle();
        return false

      });

      $('.Portfolio-box').magnificPopup({
        delegate: 'a',
        type: 'image'
      });

    });
  </script>
  <script>
    wow = new WOW({
      animateClass: 'animated',
      offset: 100
    });
    wow.init();
  </script>
  <script type="text/javascript">
    $(window).load(function() {

      $('.main-nav li a, .servicelink').bind('click', function(event) {
        var $anchor = $(this);

        $('html, body').stop().animate({
          scrollTop: $($anchor.attr('href')).offset().top - 102
        }, 1500, 'easeInOutExpo');
        /*
        if you don't want to use the easing effects:
        $('html, body').stop().animate({
          scrollTop: $($anchor.attr('href')).offset().top
        }, 1000);
        */
        if ($(window).width() < 768) {
          $('.main-nav').hide();
        }
        event.preventDefault();
      });
    })
  </script>
  <script type="text/javascript">
    $(window).load(function() {
      var $container = $('.portfolioContainer'),
        $body = $('body'),
        colW = 375,
        columns = null;
      $container.isotope({
        // disable window resizing
        resizable: true,
        masonry: {
          columnWidth: colW
        }
      });
      $(window).smartresize(function() {
        // check if columns has changed
        var currentColumns = Math.floor(($body.width() - 30) / colW);
        if (currentColumns !== columns) {
          // set new column count
          columns = currentColumns;
          // apply width to container manually, then trigger relayout
          $container.width(columns * colW)
            .isotope('reLayout');
        }
      }).smartresize(); // trigger resize to set container width
      $('.portfolioFilter a').click(function() {
        $('.portfolioFilter .current').removeClass('current');
        $(this).addClass('current');
        var selector = $(this).attr('data-filter');
        $container.isotope({

          filter: selector,
        });
        return false;
      });
    });
  </script>
</body>
</html>

lr3-4/website/main/templates/main/main.html
{% extends 'main/base.html' %}
{% block title %}
  <title>Главная страница</title>
{% endblock %}


{% block content %}
<header class="header" id="header">
    <!--header-start-->
    <div class="container">
      <figure class="logo">
        <a href="#"><img src="/static/img/logo3.png" alt=""></a>
      </figure>
      <h1 class="container">Добро пожаловать в наш магазин</h1><br><br>
      <a class="link" href="#service">Начнем</a>
    </div>
  </header>
  <!--header-end-->
  <section class="main-section" id="service">
    <!--main-section-start-->
    <div class="container">
      <h2>Категории</h2><br><br>
        <div class="container" style="margin-left:450px; margin-top:50px">
          <div class="service-list">
            <div class="service-list-col1">
              <i class="fa fa-mobile" style="margin-left:10px"></i>
            </div>
            <div class="service-list-col2" >
              <h3>Смартфоны</h3>
              <p>Phone</p>
            </div>
          </div>
          <div class="service-list">
            <div class="service-list-col1">
              <i class="fa fa-laptop"></i>
            </div>
            <div class="service-list-col2">
              <h3>Ноутбуки</h3>
              <p>Laptop</p>
            </div>
          </div>
          <div class="service-list">
            <div class="service-list-col1">
              <i class="fa fa-desktop"></i>
            </div>
            <div class="service-list-col2">
              <h3>Компьютеры</h3>
              <p>PC</p>
            </div>
          </div>
          <div class="service-list">
            <div class="service-list-col1">
              <i class="fa fa-plug"></i>
            </div>
            <div class="service-list-col2">
              <h3>Аксессуары</h3>
              <p>Accessories<p>
            </div>
          </div>

        </figure>

      </div>
    </div>
  </section>
  <!--main-section-end-->
  <section class="main-section alabaster">
    <!--main-section alabaster-start-->
    <div class="container">
      <div class="row">
        <figure class="col-lg-5 col-sm-4">
          <img src="/static/img/logo3.png" style="height:300px; weight:300px; margin-top:100px" alt="">
        </figure>
        <div class="col-lg-7 col-sm-8 featured-work">
          <h2>Наши плюсы</h2>
          <div class="featured-box" style="margin-top:100px">
            <div class="featured-box-col1">
              <i class="fa fa-magic" ></i>
            </div>
            <div class="featured-box-col2">
              <h3>Высокое качество</h3>
              <p>Только оригинальная техника</p>
            </div>
          </div>
          <div class="featured-box">
            <div class="featured-box-col1">
              <i class="fa fa-gift"></i>
            </div>
            <div class="featured-box-col2" style="margin-top:50px">
              <h3>Бонусы</h3>
              <p>При каждой покупке 10% от суммы товара вернем на бонусную карту</p>
            </div>
          </div>
          <div class="featured-box">
            <div class="featured-box-col1">
              <i class="fa fa-dashboard"></i>
            </div>
            <div class="featured-box-col2" style="margin-top:50px">
              <h3>Быстрая доставка</h3>
              <p>Доставка в течении 3-х дней по всей Беларуси</p>
            </div>
          </div>
          <a class="Learn-More" href="#">Learn More</a>
        </div>
      </div>
    </div>
  </section>
  <!--main-section alabaster-end-->

  <!--main-section client-part-end-->

  <!--c-logo-part-end-->

  <!--main-section team-end-->
  <section class="information-section" style="margin-top:50px">
    <!--business-talking-start-->
    <div class="container">
      <h2>Contact info</h2>
    </div>
  </section>
  <!--business-talking-end-->
  <div class="container">
    <section class="main-section contact" id="contact">

      <div class="row" >
        <div class="col-lg-6 col-sm-7" style="margin-top:30px">
          <div class="contact-info-box address clearfix">
            <h3><i class=" fa fa-binoculars"></i>Адресс:</h3>
            <span>ул. Пушкина<br>Дом калатушкина</span>
          </div><br>
          <div class="contact-info-box phone clearfix">
            <h3><i class="fa fa-phone"></i>Телефоны:</h3>
            <span>+375 (29) 345-45-28 <br>+375 (44) 555-73-45</span>
          </div>
          <div class="contact-info-box email clearfix">
            <h3><i class="fa fa-pencil"></i>email:</h3>
            <span>heko@fd.com</span>
          </div>
          <div class="contact-info-box hours clearfix">
            <h3><i class="fa fa-clock-o"></i>Время работы:</h3>
            <span>
              <strong>Пн - пт:</strong> 7:00 - 18:00<br>
              <strong>Сб - вс:</strong> 10:00 - 17:00
            </span>
          </div>
        </div>
        <div class="col-lg-6 col-sm-5">
          <div class="form">

          </div>
        </div>

      </div>
    </section>
  </div>
  </div>
{% endblock %}

lr3-4/website/main/templates/main/product.html
{% extends 'main/base.html' %}
{% load static %}
{% block title_page %}
  <title>Магазин</title>
{% endblock title_page %}
{% block content %}
  {% if user.is_authenticated %}


<section class="main-section paddind" id="Portfolio">

    <h2>Каталог</h2>
    <h6>У нас большой асортимент товаров.</h6>
    <div class="portfolioFilter">
      <ul class="Portfolio-nav">
        <li><a href="#" data-filter="*" class="current">Все</a></li>
        <li><a href="#" data-filter=".phone">Смартфоны</a></li>
        <li><a href="#" data-filter=".laptop">Ноутбуки</a></li>
        <li><a href="#" data-filter=".pc">Компьютеры</a></li>
        <li><a href="#" data-filter=".accesoires">Аксессуары</a></li>
      </ul>
    </div>

  </div>
  <div class="portfolioContainer">


    {% for product in pr %}
       {% if product.group == "phone" %}
          <div class=" Portfolio-box phone" style="height:400px"> <!-- Смартфоны -->
            <a href="{{ product.get_absolute_url }}">
              <img src="{{ product.img.url }}">
            </a>
            <h3>{{ product.name }}</h3>
              {% if product.availability %}
                <p>Цена: {{ product.price }} byn</p>
              {% else %}
                <p>Нет в наличии</p>
              {% endif %}
          </div>
       {% elif product.group == "pc" %}
        <div class=" Portfolio-box pc" style="height:400px"> <!-- Компьютеры -->
          <a href="{{ product.get_absolute_url }}">
              <img src="{{ product.img.url }}">
          </a>
          <h3>{{ product.name }}</h3>
            {% if product.availability %}
                <p>Цена: {{ product.price }} byn</p>
            {% else %}
                <p>Нет в наличии</p>
            {% endif %}

        </div>
       {% elif product.group == "laptop" %}
          <div class="Portfolio-box laptop" style="height:400px"> <!-- Ноутбуки -->
             <a href="{{ product.get_absolute_url }}">
              <img src="{{ product.img.url }}">
             </a>
            <h3>{{ product.name }}</h3>
              {% if post.availability %}
                <p>Цена: {{ product.price }} byn</p>
              {% else %}
                <p>Нет в наличии</p>
              {% endif %}

          </div>
       {% else %}
          <div class=" Portfolio-box accesoires" style="height:400px"> <!-- Аксессуары -->
            <a href="{{ product.get_absolute_url }}">
              <img src="{{ product.img.url }}">
            </a>
            <h3>{{ product.name }}</h3>
              {% if product.availability %}
                <p>Цена: {{ product.price }} byn</p>
              {% else %}
                <p>Нет в наличии</p>
              {% endif %}
          </div>
        {% endif %}
    {% endfor %}

  </div>
</section>
  {% else %}
    <div style="position: absolute; right: 50%; transform: translateX(50%); margin-top: 30px;">
      <h2 class="container" style="margin-top:200px">Для просмотра товаров необходимо авторизоваться</h2>
    </div>
  {% endif %}
{% endblock content %}

lr3-4/website/main/templates/main/product_details.html
{% extends 'main/base.html' %}
{% load static %}
{% block title %}
<title xmlns="http://www.w3.org/1999/html">{{ product.name }}</title>
{% endblock %}


{% block content %}
<div class="row" style="margin-top:20px">

    <figure class="col-lg-4 col-sm-4">
       <img src="{% if product.img %}{{ product.img.url }}{% else %}{% static 'img/no_image.jpg' %}{% endif %}">
    </figure>

    <div class="col-lg-7 col-sm-4 featured-work">

        <h4 style="font-size:20px; color:#222222;">{{ product.name }}</h4><br>

        <p style="color:#222222;">{{ product.description }} <br>
        <p style="color:#7cc576;">{% if product.availability %}В наличии {% else %} Нет в наличии {% endif %}</p>
        <p class="price" style="font-size:18px; margin-top:20px; margin-bottom:20px; color:#222222;">{{ product.price }} byn</p>
        {% if product.availability %}
            <form action="{% url 'cart:cart_add' product.id %}" method="post">
                {{ cart_product_form }}
                {% csrf_token %}
                <input class="btn btn-outline-primary" type="submit" value="В корзину">
            </form>
        {% else %}
        {% endif %}
    </div>
</div>
{% endblock %}
</html>